### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alt113** [traffic-control-fyp-aub/ns3-gym#31]
Go over the following C++ files and document the code:

- [x] src/traci-applications/model/traci-control-app.cc

- [x] scratch/ns3-sumo-coupling-simple.cc

The first file is where we define our agent's OpenAI Gym environment in C++ (i.e. ns3) and is the more important of the two to be documented. The second file's definition is literally in the title (or file name to be specific). It is responsible for coupling ns3 and SUMO.

--------------------------------------------------------------------------------------------------------
Here are some pointers for the functions that I feel must be documented in the `traci-control-app.cc` file (don't copy paste what I write here verbatim but follow the standard style of C++ documentation found [here](http://www.edparrish.net/common/cppdoc.html#docexample) focusing on **_Function documentation blocks_** and don't pay attention to File documentation blocks): 

- `RsuEnv::RsuEnv()`: This is the constructor of our Gym environment which we use to define our environment parameters like number of cars we will handle in our Observation Space and number of outputs in our Actions Space (notice that size of Action Space is **_N_** = number of cars while the size of Observation Space is **_2N_**). Once this constructor is called the ZMQ bridge is set up between ns3 (C++) and the RL Agent (python).

- `Ptr<OpenGymSpace> RsuEnv::GetObservationSpace()`:  Even though it is named as a getter in reality it is in charge of sending our Observation Space definition to the RL Agent which needs to know "the name of the game" of the environment it will be working on.

- `Ptr<OpenGymSpace> RsuEnv::GetActionSpace()`:  You get the point here, just like the `GetObservationSpace()` function.

- `Ptr<OpenGymDataContainer> RsuEnv::GetObservation()`: Whenever our RL Agent needs to predict an action it needs to know the current state of the environment. This function is called to collect the state of the environment (i.e. create an array of size **_2N_** with the first **_N_** elements being the headways of the vehicles at time step **_T_** and the last **_N_** elements are the velocities).

- `float RsuEnv::GetReward()`: After the RL Agent has predicted actions and we physically applied these actions to the vehicles in our environment the agent needs to know how good was it's previously predicted actions to learn to perform better. Hence, we call this function to compute the reward and send it to the agent over the ZMQ bridge.

- `bool RsuEnv::GetGameOver()`: Sometimes the RL agent reaches an end state in training. In our case it could be either an accident has occurred or the reward is not really changing that much after so many time steps. In any case we must prematurely terminate the episode of training.

- `bool RsuEnv::ExecuteActions(Ptr<OpenGymDataContainer> action)`: This function receives the predicted actions from the RL Agent and physically implements them on the vehicles in SUMO.

- `std::vector<float> RsuEnv::ExportNewSpeeds()`: Helper function to export the speeds of vehicles from SUMO (to send to the agent later through the observation space). Basically this is our zero-padding function that makes sure to handle any instance where there is a mismatch between the number of vehicles on the traffic scenario and the size of our Observation and Action Spaces.

- `void RsuEnv::ImportSpeedsAndHeadWays(std::vector<double> RSU_headways, std::vector<double> RSU_speeds)`: Helper function to import the speeds and headways from SUMO.

**Comment by alt113** [comment]
@AhmadAbouAdla1 I've updated the title comment of this issue with enough info for you to get to work, check it out.

**Comment by AhmadAbouAdla1** [comment]
Do you mean src/traci-applications/model/traffic-control-app.cc?

**Comment by alt113** [comment]
I mean both those files but I want to make sure the RSU environment in ns3 is properly documented because it is very important.

**Comment by AhmadAbouAdla1** [comment]
Okay

**Comment by AhmadAbouAdla1** [comment]
@alt113 I can't find rc/traci-applications/model/traci-control-app.cc is it renamed to traffic-control-app.cc?

**Comment by alt113** [comment]
@AhmadAbouAdla1 yes, my bad it was renamed. Also the functions I listed in the original comment are in a file called `rsu-environment.cc`. @jKh98 did a good job with the header file but the `.cc` file also needs documentation. Also, now that you've mentioned it so could the `traffic-control-app.cc`  since it is really important in our system architecture.

**Comment by AhmadAbouAdla1** [comment]
I finished rsu-environment.cc but I didn't know what std::string RsuEnv::GetExtraInfo () and void
RsuEnv::DoDispose () did. Will start tomorrow with traffic-control-app.cc.

**Comment by AhmadAbouAdla1** [comment]
Also, for some reason, Travis is failing one of my commits (uint32_...). Can you please look into it @alt113 ?

**Comment by alt113** [comment]
@AhmadAbouAdla1 I took a look into the travis build that failed. Don't worry about it since it seemed like an isolated scenario and since the tests have nothing to do with the code you are submitting.

**Comment by AhmadAbouAdla1** [comment]
Perfect

**Comment by alt113** [comment]
Closing this now.
