### ISSUE TITLE
System Avg Speed [ Performance ]

### ISSUE THREAD

**Issue by alt113** [traffic-control-fyp-aub/ns3-gym#37]
Study the effect of different vehicle control percentages (incorporate human driver control) on the system wide average speed and whether it increases or decreases.

**Comment by alt113** [comment]
@AhmadAbouAdla1 
I varied two variables which are the number of controlled cars and the headway value. Varrying the headway for a fixed number of cars controlled (25 cars) did not change the system avg speed. Varrying the number of cars controlled (10 cars) while keeping the headway stable (one at 1 second and once at 2 seconds) resulted in both cases in an even lower system avg speed and more spikes in system std dev speed.

In all cases my results are pushed and available to be reviewed.

**Comment by alt113** [comment]
@AhmadAbouAdla1 
I varied two variables which are the number of controlled cars and the headway value. Varrying the headway for a fixed number of cars controlled (25 cars) did not change the system avg speed. Varrying the number of cars controlled (10 cars) while keeping the headway stable (one at 1 second and once at 2 seconds) resulted in both cases in an even lower system avg speed and more spikes in system std dev speed.

In all cases my results are pushed and available to be reviewed.

**Comment by alt113** [comment]
@AhmadAbouAdla1 @jKh98 Closing this issue.

**Comment by AhmadAbouAdla1** [comment]
I reviewed and confirm your findings.
